### ISSUE TITLE
Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by ajjunaedi** [yusriltakeuchi/stamp_image#1]
`E/flutter (13310): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: No element
E/flutter (13310): #0      List.first (dart:core-patch/array.dart:305:5)
E/flutter (13310): #1      StampImage.create (package:stamp_image/stamp_image.dart:21:67)
E/flutter (13310): <asynchronous suspension>`

When I try to implement the library according to the example, I get an error like this. Is there any solution? Thank u

**Comment by sunpulun** [comment]
same iuuues

**Comment by lucasvps** [comment]
Same here

**Comment by yusriltakeuchi** [comment]
Halo, this problem fixed in the new version.
Please update your dependency to 0.0.2.

stamp_image: ^0.0.2
